In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random(200).reshape(2, 100))
# Set up display area to show dataframe in jupyter qtconsole
# pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
0,0.626658,0.283862,0.910360,0.073348,0.939331,0.961144,0.929551,0.011990,0.800510,0.507153,0.518245,0.063798,0.921654,0.400112,0.175853,0.013648,0.113662,0.004081,0.041983,0.990527,0.815854,0.652338,0.823156,0.503787,0.823016,0.795440,0.885825,0.762777,0.630905,0.851752,0.799218,0.468004,0.335268,0.312891,0.763215,0.204169,0.451008,0.404841,0.936014,0.812447,0.607132,0.426392,0.132704,0.185898,0.441664,0.384361,0.409871,0.746947,0.452775,0.437514,0.298156,0.082107,0.889892,0.216171,0.642693,0.352863,0.731503,0.991338,0.110377,0.507787,0.564618,0.973932,0.219260,0.547184,0.060766,0.226415,0.038606,0.961078,0.316493,0.156124,0.092972,0.903720,0.894578,0.383583,0.914831,0.241380,0.602471,0.553800,0.905508,0.106414,0.224020,0.755913,0.635291,0.438217,0.902727,0.975965,0.363819,0.698744,0.760381,0.663363,0.949864,0.957205,0.032878,0.349068,0.718632,0.428192,0.622923,0.817436,0.451510,0.682092
1,0.114952,0.988351,0.219578,0.713289,0.212938,0.139256,0.237243,0.555601,0.673658,0.330155,0.796449,0.962832,0.257455,0.612604,0.141519,0.658961,0.901903,0.153114,0.876018,0.306803,0.709027,0.006164,0.847027,0.659257,0.186605,0.831235,0.947704,0.641896,0.329161,0.428930,0.852555,0.165534,0.886604,0.838572,0.141331,0.963505,0.979104,0.067524,0.086081,0.551056,0.429676,0.812993,0.370307,0.695523,0.731200,0.944761,0.998294,0.607815,0.786661,0.561492,0.275041,0.344614,0.983895,0.686143,0.942828,0.400988,0.545405,0.126376,0.435524,0.056510,0.003873,0.840536,0.268515,0.285835,0.766288,0.018848,0.334525,0.861793,0.894724,0.142151,0.112428,0.306338,0.572600,0.993821,0.598065,0.141736,0.694122,0.726753,0.145105,0.679183,0.144051,0.697773,0.373445,0.945656,0.628709,0.832149,0.793575,0.376861,0.038857,0.092606,0.262802,0.731569,0.953786,0.718742,0.917738,0.861622,0.714865,0.986507,0.352088,0.003847

In [2]:
string_x = "if the df has a lot of rows or columns, then when you try to show the df, pandas will auto detect \
the size of the displaying area and automatically hide some part of the data by replacing with"
pd.DataFrame({'string_x': string_x}, index = [0])

                                            string_x
0  if the df has a lot of rows or columns, then w...

In [3]:
spark.createDataFrame(
  [('2018-08-20', 1.0), ('2018-08-21', 2.0), ('2018-08-24', 3.0)], 
  ['time', 'v']
).toPandas()

NameError: name 'spark' is not defined

In [ ]:
array = np.array([[1,2,3], [4,5,6]])
print(np.array2string(array).replace('[[',' [').replace(']]',']'))
pd.DataFrame(array)

In [ ]:
# if input image is in range 0..1, please first multiply img by 255
# assume image is ndarray of shape [height, width, channels] where channels can be 1, 3 or 4
def imshow(img):
    import cv2
    import IPython
    _,ret = cv2.imencode('.jpg', img) 
    i = IPython.display.Image(data=ret)
    IPython.display.display(i)

import numpy as np
src = np.zeros((128, 128, 3))
src+=0.2
src[40:60, 60:100] += 0.3
src[50:90, 20:70] += 0.2

imshow(src*255)

In [ ]:
import numpy as np
m = np.zeros((128, 128, 3))
m+=0.2
m[40:60, 60:100] += 0.3
m[50:90, 20:70] += 0.2
m